site_name: Ding Ding Ding Wiki
site_url: https://ab3loth.github.io/jull-aotr-wiki
theme:
  name: material
  logo: assets/images/logo.png
  palette:
    primary: black
    accent: indigo

nav:
  - Home: index.md
  - Regiment: regiment.md
